// src/app/app.component.ts
import { Component } from "@angular/core"
import { CommonModule } from "@angular/common"
import { DashboardComponent } from "./components/dashboard/dashboard.component"

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule, DashboardComponent],
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "Dynamic Angular Dashboard"
}

<div class="container mx-auto p-4">
  <h1 class="text-2xl font-bold mb-6">Your Personalized Dashboard</h1>
  <p class="mb-6 text-muted-foreground">
    Customize your dashboard with drag-and-drop cards. Cards in the same row maintain consistent height.
  </p>
  <app-dashboard></app-dashboard>
</div>

// app/page.tsx
import Dashboard from "@/components/dashboard"

export default function Home() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-6">Your Personalized Dashboard</h1>
      <p className="mb-6 text-muted-foreground">
        Customize your dashboard with drag-and-drop cards. Cards in the same row maintain consistent height.
      </p>
      <Dashboard />
    </div>
  )
}
