// src/app/components/dashboard-card/dashboard-card.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core"
import { CommonModule } from "@angular/common"

@Component({
  selector: "app-dashboard-card",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./dashboard-card.component.html",
  styleUrls: ["./dashboard-card.component.css"],
})
export class DashboardCardComponent {
  @Input() title = ""
  @Input() content = ""
  @Input() color = "bg-card"
  @Input() isEditing = false
  @Input() size = 1
  @Input() canIncrease = true
  @Input() canDecrease = true

  @Output() increaseSize = new EventEmitter<void>()
  @Output() decreaseSize = new EventEmitter<void>()
  @Output() remove = new EventEmitter<void>()
}

<div class="card {{color}} transition-all duration-200 hover:shadow-md h-full flex flex-col"
     [ngClass]="{'ring-2 ring-primary/20': isEditing}">
  <div class="card-header flex flex-row items-center justify-between pb-2">
    <div class="flex items-center gap-2">
      <div *ngIf="isEditing" class="cursor-move text-primary mr-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-grip-vertical">
          <circle cx="9" cy="12" r="1"/><circle cx="9" cy="5" r="1"/><circle cx="9" cy="19" r="1"/>
          <circle cx="15" cy="12" r="1"/><circle cx="15" cy="5" r="1"/><circle cx="15" cy="19" r="1"/>
        </svg>
      </div>
      <h3 class="card-title text-lg font-medium truncate">{{title}}</h3>
    </div>
    <div class="flex items-center gap-2">
      <button *ngIf="isEditing" class="btn btn-ghost h-7 w-7" (click)="decreaseSize.emit()" [disabled]="!canDecrease">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-minimize-2">
          <polyline points="4 14 10 14 10 20"/><polyline points="20 10 14 10 14 4"/>
          <line x1="14" y1="10" x2="21" y2="3"/><line x1="3" y1="21" x2="10" y2="14"/>
        </svg>
        <span class="sr-only">Decrease size</span>
      </button>
      <button *ngIf="isEditing" class="btn btn-ghost h-7 w-7" (click)="increaseSize.emit()" [disabled]="!canIncrease">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-maximize-2">
          <polyline points="15 3 21 3 21 9"/><polyline points="9 21 3 21 3 15"/>
          <line x1="21" y1="3" x2="14" y2="10"/><line x1="3" y1="21" x2="10" y2="14"/>
        </svg>
        <span class="sr-only">Increase size</span>
      </button>
      <button *ngIf="isEditing" class="btn btn-ghost h-7 w-7 text-destructive hover:text-destructive" (click)="remove.emit()">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trash-2">
          <path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/>
          <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/><line x1="10" y1="11" x2="10" y2="17"/>
          <line x1="14" y1="11" x2="14" y2="17"/>
        </svg>
        <span class="sr-only">Remove card</span>
      </button>
    </div>
  </div>
  <div class="card-content flex-1 flex flex-col">
    <p class="mb-4">{{content}}</p>
    <div class="mt-auto h-24 flex items-center justify-center rounded-md bg-background/50">
      <!-- Placeholder for card content -->
      <span class="text-sm text-muted-foreground">
        <ng-container *ngIf="isEditing">{{size}} column{{size > 1 ? 's' : ''}}</ng-container>
        <ng-container *ngIf="!isEditing">Card Content</ng-container>
      </span>
    </div>
  </div>
</div>

// components/dashboard-card.tsx
"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { GripVertical, Maximize2, Minimize2, Trash2 } from "lucide-react"

interface DashboardCardProps {
  title: string
  content: string
  color?: string
  isEditing?: boolean
  size?: number
  onIncreaseSize?: () => void
  onDecreaseSize?: () => void
  onRemove?: () => void
  canIncrease?: boolean
  canDecrease?: boolean
}

export default function DashboardCard({
  title,
  content,
  color = "bg-card",
  isEditing = false,
  size = 1,
  onIncreaseSize,
  onDecreaseSize,
  onRemove,
  canIncrease = true,
  canDecrease = true,
}: DashboardCardProps) {
  return (
    <Card
      className={`${color} transition-all duration-200 hover:shadow-md h-full flex flex-col ${
        isEditing ? "ring-2 ring-primary/20" : ""
      }`}
    >
      <CardHeader className="flex flex-row items-center justify-between pb-2">
        <div className="flex items-center gap-2">
          {isEditing && (
            <div className="cursor-move text-primary mr-2">
              <GripVertical size={20} />
            </div>
          )}
          <CardTitle className="text-lg font-medium truncate">{title}</CardTitle>
        </div>
        <div className="flex items-center gap-2">
          {isEditing && (
            <>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={onDecreaseSize} disabled={!canDecrease}>
                <Minimize2 size={16} />
                <span className="sr-only">Decrease size</span>
              </Button>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={onIncreaseSize} disabled={!canIncrease}>
                <Maximize2 size={16} />
                <span className="sr-only">Increase size</span>
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 text-destructive hover:text-destructive"
                onClick={onRemove}
              >
                <Trash2 size={16} />
                <span className="sr-only">Remove card</span>
              </Button>
            </>
          )}
        </div>
      </CardHeader>
      <CardContent className="flex-1 flex flex-col">
        <p className="mb-4">{content}</p>
        <div className="mt-auto h-24 flex items-center justify-center rounded-md bg-background/50">
          {/* Placeholder for card content */}
          <span className="text-sm text-muted-foreground">
            {isEditing ? `${size} column${size > 1 ? "s" : ""}` : "Card Content"}
          </span>
        </div>
      </CardContent>
    </Card>
  )
}
